spring.application.name=water_delivery

spring.datasource.url=jdbc:mysql://localhost:3306/water_delivery
spring.datasource.username=root
spring.datasource.password=


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##
# With Hibernate, this will automatically create/update tables from your entity classes.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
